source ~/.dotfiles/zshrc/zshrc
source ~/.dotfiles/zshrc/others.zsh
source ~/.dotfiles/zshrc/env.zsh
source ~/.dotfiles/zshrc/binds.zsh
source ~/.dotfiles/zshrc/filesystem.zsh
source ~/.dotfiles/zshrc/autosuggestations.zsh
source ~/.dotfiles/zshrc/cd.zsh
source ~/.dotfiles/zshrc/clipboard.zsh
source ~/.dotfiles/zshrc/coreutils.zsh
source ~/.dotfiles/zshrc/kanata.zsh
source ~/.dotfiles/zshrc/man.zsh
source ~/.dotfiles/zshrc/niri.zsh
source ~/.dotfiles/zshrc/transmission.zsh
source ~/.dotfiles/zshrc/terminal.zsh
source ~/.dotfiles/zshrc/yazi.zsh
source ~/.dotfiles/zshrc/topgrade.zsh
source ~/.dotfiles/zshrc/timedatectl.zsh
source ~/.dotfiles/zshrc/go.zsh
source ~/.dotfiles/zshrc/path.zsh
source ~/.dotfiles/zshrc/nixos.zsh
source ~/.dotfiles/zshrc/doas.zsh
source ~/.dotfiles/zshrc/network.zsh
source ~/.dotfiles/zshrc/wayland.zsh
