if [ "$(tty)" = "/dev/tty1" ]; then
    niri-session
fi
ZSH_COMPDUMP="${ZDOTDIR:-$HOME}/.zcompdump"

autoload -Uz compinit
compinit

if [[ ! -f "$ZSH_COMPDUMP.zwc" || "$ZSH_COMPDUMP" -nt "$ZSH_COMPDUMP.zwc" ]]; then
  zcompile "$ZSH_COMPDUMP"
fi
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

HISTFILE=~/.zsh_history
HISTSIZE=999999999999999
SAVEHIST=999999999999999
HISTDUP=erase
setopt AUTO_CD
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone git@github.com:zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load Zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in Powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Essential zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
# zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit load 'zsh-users/zsh-history-substring-search'
zinit ice wait atload'_history_substring_search_config'
zinit ice silent; zinit light Aloxaf/fzf-tab

# Add in snippets
zinit snippet OMZP::sudo
zinit snippet OMZP::git
# zinit snippet OMZP::command-not-found
# zinit snippet OMZP::archlinux
# unfunction paclist


zinit cdreplay -q

[[ ! -f ~/.dotfiles/zshrc/.p10k.zsh ]] || source ~/.dotfiles/zshrc/.p10k.zsh

BINDIR="${XDG_BIN_HOME:-$HOME/.local/bin}"

if ! echo $PATH | grep "$BINDIR" >/dev/null 2>&1; then
	export PATH="$PATH:$BINDIR"
fi
autoload bashcompinit
bashcompinit
source "/home/aziz/.local/share/bash-completion/completions/appman"

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

eval "$(zoxide init --cmd cd zsh)"
eval "$(fzf --zsh)"
bindkey -r "^[c"
bindkey -r "^T"
