monitorrule=name:^eDP-1$,make:Lenovo Group Limited,width:1920,height:1200,refresh:60,x:0,y:0,scale:1.6,disable
monitorrule=name:DP-1,width:3840,height:2160,refresh:60,x:1200,y:0,scale:2.4
bind=ctrl,m,spawn,notify-send hello
exec-once=wl-paste --type image --watch cliphist store
exec-once=wl-paste --type text --watch cliphist store
exec-once=gammastep
exec-once=solaar --window=hide
bind=NONE,F13,switch_keyboard_layout
xkb_rules_layout=us,ru
bind=super,tab,focusstack,next
rootcolor=0x00000000

bind=super,r,spawn,rofi -show drun
bind=super,return,spawn,foot
bind=super,s,reload_config

bind=super,m,quit
bind=super,b,killclient
bind=super,f,togglefullscreen
bind=super+shift,f,togglefakefullscreen
bind=ALT,a,togglemaximizescreen,
mouse_natural_scrolling=0
bind=super,h,focusdir,left
bind=super,i,focusdir,right
bind=super,e,focusdir,up
bind=super,a,focusdir,down
bind=super+shift,i,tagtoright
bind=super+shift,h,tagtoleft

bind=Ctrl,1,view,1,0
bind=Ctrl,2,view,2,0
bind=Ctrl,3,view,3,0
bind=Ctrl,4,view,4,0
bind=Ctrl,5,view,5,0
bind=Ctrl,6,view,6,0
bind=Ctrl,7,view,7,0
bind=Ctrl,8,view,8,0
bind=Ctrl,9,view,9,0

bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,
bind=super,n,setlayout,scroller
bind=super,Left,scroller_stack,left
bind=super,Right,scroller_stack,right
bind=super,Up,scroller_stack,up
bind=super,Down,scroller_stack,down
bind=super,u,viewtoleft
bind=super,o,viewtoright
